# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170401_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygeo',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.City'),
        ),
    ]
