# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mygeo_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygeo',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.City'),
        ),
    ]
