# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170401_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='timezone',
        ),
    ]
