# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_city_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='province',
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Region'),
        ),
    ]
