# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170401_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
