# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_province_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(default='province', max_length=100, null=True),
        ),
    ]
