# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170401_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
